---
- name: Playbook testowy3 dla Cisco
  gather_facts: no 
  hosts: r1.private
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: user
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'

  tasks:
    - name: Konfiguracja listy ACL
      ios_config:
        lines:
          - access-list 99 permit 111.111.111.111

    - name: Weryfikacja czy lista ACL została faktycznie skonfigurowana
      ios_command:
        commands:
          - show access-lists
        waitfor:
          - result[0] contains 'permit 111.111.111.111'

    - name: Zapisanie zmodyfikowanej konfiguracji
      ios_config:
        save_when: modified

    - name: Pobieranie informacji z urządzeń cisco
      ios_command:
        commands:
        - show access-lists
      register: wynik_show
    
    - debug: var=wynik_show.stdout_lines
