---
# tasks file for ./roles/keepalived_haproxy

- name: Konfiguracja wstępna serwerów web i lb
  include_tasks: konfiguracja_wstepna.yaml
  when: (inventory_hostname == "lb1.private") or (inventory_hostname == "lb2.private") or (inventory_hostname == "web1.private") or (inventory_hostname == "web2.private")
  tags: konfiguracja_wstepna

- name: Utworzenie użytkowników na serwerach WEB i LB
  include_tasks: tworzenie_uzytkownikow.yaml
  tags: tworzenie_uzytkownikow

- name: instalacja oprogramowania na serwerach WEB
  include_tasks: instalacja_web.yaml
  when: (ansible_nodename == "web1.private") or (ansible_nodename == "web2.private")
  tags: instalacja_web

- name: instalacja oprogramowania na serwerach LB
  include_tasks: instalacja_lb.yaml
  when: (ansible_nodename == "lb1.private") or (ansible_nodename == "lb2.private")
  tags: instalacja_lb
