---
- name: Playbook do sprawdzenia zajętości dysków
  hosts: serweryweb
  gather_facts: yes

  tasks:
  - name: Sprawdzenie zajętości dysków
    command: df -h --output=pcent,target
    register: disk_usage

  - name: Analiza użycia dysków
    set_fact:
      partitions: "{{ disk_usage.stdout_lines[1:] | map('split') | map('last') | list }}"
      usage: "{{ disk_usage.stdout_lines[1:] | map('split') | map('first') | list }}"

  - name: Sprawdź partycje z wykorzystaniem ponad 80%
    set_fact:
      high_usage_partitions: "{{ partitions | zip(usage) | selectattr('1', 'search', '^8[0-9]|^9[0-9]|100%') | list }}"
#      high_usage_partitions: "{{ partitions | zip(usage) | selectattr('1', 'search', '^[0-9]|^1[0-9]|^2[0-9]|^3[0-9]|100%') | list }}"
      
  - name: Sprawdzanie, czy są partycje z mniejszą ilością wolnego miejsca niż 20%
    debug:
      msg: "Następujące partycje mają mniej niż 20% wolnego miejsca: {{ high_usage_partitions }}"
    when: high_usage_partitions | length > 0

  - name: Wysłanie powiadomienia do Gotify, jeśli są partycje z małą ilością wolnego miejsca
    uri:
      url: "http://192.168.122.201:6789/message?token=ACXUcmbt9wnsVvQ"
      method: POST
      body_format: json
      body: 
        title: "Mało miejsca na patycji serwera {{ansible_hostname}}"
        message: "Uwaga! Na następujących partycjach serwera {{ansible_hostname}} jest mniej niż 20% wolnego miejsca: {{ high_usage_partitions | join(', ') }}."
    when: high_usage_partitions | length > 0
