- name: Playbook realizujący pełną konfigurację serwerów web i lb
  hosts: serweryweb,loadbalancers,local
  gather_facts: yes # chcemy zbierać informacje o urządzeniach
  vars:
    uzytkownicy_dla_web_lb:
      - mkowalski
      - jgula
      - pszary

  tasks:
    - name: Konfiguracja wstępna serwerów web i lb
      include_tasks: konfiguracja_wstepna.yaml
      when: (ansible_nodename == "lb1.private") or (ansible_nodename == "lb2.private") or (ansible_nodename == "web1.private") or (ansible_nodename == "web2.private")
      tags: konfiguracja_wstepna
  
    - name: Utworzenie użytkowników na serwerach WEB i LB
      include_tasks: tworzenie_uzytkownikow.yaml
      tags: tworzenie_uzytkownikow


    - name: instalacja oprogramowania na serwerach LB
      include_tasks: ./serwery_lb/instalacja_lb.yaml
      when: (ansible_nodename == "lb1.private") or (ansible_nodename == "lb2.private")
      tags: instalacja_lb




